name: Metrics
on:
  # Schedule updates (every 12 hours)
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: pranavkapale
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_lines: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 10

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: github-achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: pranavkapale
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
